[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "wxbox-utils"
version = "0.1.0"

description = "WxBox utilities for HRRR, FV3 grid and restart generation, JEDI LETKF cycling, diagnostics, and visualization"

readme = "README.md"

requires-python = ">=3.10"

dependencies = [
    "numpy>=1.24",
    "scipy>=1.10",
    "pandas>=2.0",

    "xarray>=2023.1",
    "netCDF4>=1.6",

    "PyYAML>=6.0",
    "Jinja2>=3.1",

    "matplotlib>=3.7",
    "cartopy>=0.22",

    "boto3>=1.34",
    "botocore>=1.34",

    "cfgrib>=0.9.10"
]

[tool.setuptools.package-data]

wxbox_utils = [
    "configs/templates/*.j2"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["wxbox_utils*"]

[project.scripts]

# LETKF
wxbox-letkf = "wxbox_utils.drivers.letkf_driver:main"

# Post Processing
wxbox-plot = "wxbox_utils.drivers.plot_driver:main"
wxbox-density = "wxbox_utils.post.experiment_density:main"
wxbox-movie = "wxbox_utils.post.movie_builder:main"

# Ensemble
wxbox-gen-ens = "wxbox_utils.ensemble.gen_ens:main"

# Observation Database
wxbox-build-obsdb = "wxbox_utils.obs.build_obsdb_cycles:main"

# Grid Utilities
wxbox-create-grid = "wxbox_utils.grid.create_esg_grid:main"
wxbox-create-mosaic = "wxbox_utils.grid.create_mosaic:main"

# HRRR Utilities

wxbox-download-hrrr = "wxbox_utils.hrrr.download_hrrr:main"

wxbox-hrrr-to-fv3 = "wxbox_utils.hrrr.hrrr_to_fv3_restart:main"