grid:
  name: C417

  #
  # NEW
  #
  source_grid:
    Data/inputs/lam_rrfs/INPUT/C403_grid.tile7.halo3.nc

  target_lon: -79.5
  target_lat: 38.5

  idim: 61
  jdim: 41

  delx: 0.108
  dely: 0.108

  halo: 3

  output:
    grid_file: Data/inputs/lam_c417/INPUT/C417_grid.tile7.nc

  mosaic:
    template: Data/inputs/lam_rrfs/INPUT/C403_mosaic.halo3.nc
    output: Data/inputs/lam_c417/INPUT/C417_mosaic_rrfsstyle.nc

background:

  src_dir: Data/inputs/lam_rrfs/bkg
  dst_dir: Data/inputs/lam_c417/bkg

  files:

    - src: 20201215.000000.rrfs_C403.fv_core.res.tile1.nc
      dst: 20201215.000000.rrfs_C417.fv_core.res.tile1.nc

    - src: 20201215.000000.rrfs_C403.fv_tracer.res.tile1.nc
      dst: 20201215.000000.rrfs_C417.fv_tracer.res.tile1.nc

    - src: 20201215.000000.rrfs_C403.fv_srf_wnd.res.tile1.nc
      dst: 20201215.000000.rrfs_C417.fv_srf_wnd.res.tile1.nc

    - src: 20201215.000000.rrfs_C403.sfc_data.nc
      dst: 20201215.000000.rrfs_C417.sfc_data.nc

coupler:

  src:
    Data/inputs/lam_rrfs/bkg/20201215.000000.rrfs_C403.coupler.res

  dst:
    Data/inputs/lam_c417/bkg/20201215.000000.rrfs_C417.coupler.res

interpolation:
  method: linear