experiment:

  name:
    tempest_c1667

cycles:

  root:
    runs/hrrr_bdp

grid:

  name:
    C1667

  akbk:
    Data/inputs/lam_akbk/INPUT/akbk65.nc

  grid_file:
    Data/inputs/lam_c1667/INPUT/C1667_grid.tile7.nc

  template_dir:
    Data/inputs/lam_c1667/bkg

output:

  root:
    runs/c1667

templates:

  core:
    20201215.000000.rrfs_C1667.fv_core.res.tile1.nc

  tracer:
    20201215.000000.rrfs_C1667.fv_tracer.res.tile1.nc

  sfcw:
    20201215.000000.rrfs_C1667.fv_srf_wnd.res.tile1.nc

  sfcd:
    20201215.000000.rrfs_C1667.sfc_data.nc